sudo: true

language: python
python:
  - '2.7'

before_install:
  - whoami

install:
  - pip install ansible
  - pip install pexpect

before_install:
  - ansible --version
  - ansible-playbook -i hosts site.yaml  --syntax-check

script:
  - ansible-playbook -i hosts site.yaml

notifications:
  slack:
    secure: aOYAzQT0OXmrRKfCFWBiks+nt6TQbD98eXcv7K1A2Ju5JdBzYvIfJ2VZnQep5xtBcfn9yAOTvFmuAz6YUt3qrP39Z8EUpGB5Uk/5vt/mbh0V79XPx1SDJBypcRrqnhAB1N8VukCZhmYeQmIBUKDQCdjiR+f7NMZGDtKd+T3H6xq1ZZ63rWY4h7z/nZW0O+7RXCqlUvETJ3KBrdb6F2Lf+h1QrDncg02pk2t6yPymMVnibfpK6vlX4iKV2cxKJyUUb7TDOjqyf9DkYX93igNuEc5uRQeCZ1aj812T8lfyjUr2O2jJf5n989+EqrKH4Ps3YUGmvd+chtyrrRX4bGe73FL9Ptk7odIwGyTlQ4McVLjV0uyeUWwa9T+8H1INqh7v2NQzx8jciLrib0P9bAj3Kne64wd39NRsfPddRsdyjJCmBKyfY9ogg6uXO2Cc9v5EgdeWEOIKalFbGiZCULSxQ/fIbms6XXtpOwaGUq6VHwdps8H8N0rhg14iU5w3u2wYpu+hzx5chG6P2VEAV/dZrX8ngzaaT88ZhsXqJcaubEyhfqlzCiVxAh8vMwzYfYBq4A2HC774cmPyr7+9eEn3ml5KdEWnfTmueoqTK9ipqpTUv1MyI1s6KqcMfCTtUHbXK44JpZ6HuObQZ6mCITqJHfyOhYwWXonetXTZYTv54IM=
